name: course-analyzer-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - pandas
  - numpy
  - streamlit
  - pip:
      - transformers
      - datasets
      - torch
      - torchvision
      - torchaudio
      - seaborn
      - scikit-learn
      - sentencepiece
      - huggingface-hub
      - bs4
      - lxml
      - aiohttp
      - memory-profiler
      - matplotlib-inline
      - pydeck
      - tqdm
